name: test-github-actions
on: [push]
jobs:
  check-archlinux-version:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest
    steps:
      - uses: actions/checkout@v3
      - run: echo -e "zh_CN.UTF-8 UTF-8\nzh_HK.UTF-8 UTF-8\n\nen_US.UTF-8 UTF-8\nja_JP.UTF-8 UTF-8" >> /etc/locale.gen && locale-gen
      - run: locale -a
      - run: pacman -Syu --noconfirm --needed plantuml texlive-most noto-fonts-cjk yarn ditaa pelican make inkscape opencc graphviz parallel optipng git
      - run: git clone https://github.com/farseerfc/pelican-bootstrap3.git theme
      - run: git clone https://github.com/farseerfc/pelican-plugins.git plugins
      - run: install -dm755 tikz2svg /usr/local/bin/tikz2svg
      - run: SITEURL=farseerfc.me make publish
      - run: bash renderpdf.sh
